# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: RH Class - aulinha de DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compilando os arquivos java main
      run: |
        cd src
        javac -cp . Main.java
    - name: Compilando os arquivos java - Teste unitário
      run: |
        cd src
        javac -cp . Teste.java
    - name: Executando o projeto Java
      run: |
        cd src
        java -cp . Teste
        
